Make menu into sidebar #89
diballesteros/nuzlocke pull request #92
Opened 2021-08-29 05:49 UTC by RyoMasumura1201

This is from issue #89

2021-08-29 12:35 UTC, diballesteros requested changes
Everything look's great for the most part!

If you can, please send the updated PR to version/3.4.0. This so all the changes can be batched together for the next version. I'll be sure to update the contributing.md for this to be taken into consideration in future contributions.

I also went ahead and added a slight style change to the hidden file input to avoid the overflow  in the sidebar.

Thank you so much for your contribution!

2021-08-29 12:35 UTC, diballesteros commented on src/App.module.scss
> +    background-color: white;
Use the css variable var(--header) for the background color of the header button to take in the darkmode colors and var(--contrast) for the font color

2021-08-29 12:35 UTC, diballesteros commented on src/App.tsx
> +          <Settings />
For <Settings /> <Contact  /> <About /> and <Changelog /> change the trigger to a <Menu.Item /> instead of the <Dropdown.Item />

2021-08-30 22:17 UTC, RyoMasumura1201 commented
@diballesteros 
Thank you for your review!
I've fixed the points you pointed out, so please check back.

2021-08-30 22:58 UTC, diballesteros commented
close #92

2021-08-30 22:58 UTC, merged